spring.application.name=shipping-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/shipping_db
spring.datasource.username=postgres
spring.datasource.password=Vaibhav#08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true